export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SAVE_DISCLIST = 'SAVE_DISCLIST'

export const SAVE_SONGLIST = 'SAVE_SONGLIST'

export const SAVE_RADIOLIST= 'SAVE_RADIOLIST'

export const SAVE_SIDERLIST= 'SAVE_SIDERLIST'

export const SAVE_SONG= 'SAVE_SONG'
